# This file will server as an example to test out all the endpoints.


# API CONFIG
@BASE_PATH=http://localhost:3000/api/v1
@AUTH_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6Ijc0NTRjMzA1LTc5MGYtNDU4OC1hYWZkLTVhM2UwZTM4MDJhZCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzODY5Mjc1NiwidXNlcl9pZCI6IjNkZjNiNTc3LWE4ODAtNDE4Ni1hNzQ2LWRkYTZmMDUzNThhYSJ9.LEaO0Xd8xwNEboZHBDkJogKOpncz7MEapnyMEHFvarI

# Register Request
POST {{BASE_PATH}}/register
Content-Type: application/json

{
  "email": "sriprabandham@gmail.com",
  "name": "Srinidhi P",
  "password": "SuperSecure"
}
####

# LOGIN Request
POST {{BASE_PATH}}/login
Content-Type: application/json

{
  "email": "sriprabandham@gmail.com",
  "password": "SuperSecure"
}
####

# List all credit types
GET {{BASE_PATH}}/credit_types?page=1&per_page=10
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####

# Create an credit type
POST {{BASE_PATH}}/credit_types
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}

{
  "name": "Consultation"
}
####

# List all debit types
GET {{BASE_PATH}}/debit_types?page=1&per_page=10
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####

# Create a debit type
POST {{BASE_PATH}}/debit_types
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}

{
  "name": ""
}
####

# List all accounts for the logged in user
GET {{BASE_PATH}}/accounts?page=1&per_page=10
Authorization: {{AUTH_TOKEN}}
###

# Create Account
POST {{BASE_PATH}}/accounts
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}

{
  "name": "Axis Bank",
  "address": "Axis Bank Kormangala",
  "ifsc_code": "IFSC004",
  "available_balance": 5000
}
###

# List all credits for logged in user
GET {{BASE_PATH}}/credits?page=1&per_page=10
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####

# Create an income record for logged in user.
POST {{BASE_PATH}}/credits
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}

{
  "credit_type_id": "",
  "amount": 100,
  "account_id": "",
  "credited_on": "2021-12-01T11:50:01.079Z"
}
###

# List all expenses for logged in user
GET {{BASE_PATH}}/debits?page=1&per_page=10
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####

# Create a debit for logged in user.
POST {{BASE_PATH}}/debits
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}

{
  "debit_type_id": "",
  "amount": 100,
  "account_id": "",
  "debited_on": "2021-12-01T11:50:01.079Z"
}
###

# Logout
DELETE {{BASE_PATH}}/logout
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####
