# This file will server as an example to test out all the endpoints.


# API CONFIG
@BASE_PATH=http://localhost:3000/api/v1
@AUTH_TOKEN=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImY0ZTQ4Mjc2LTk4NzEtNDY0My04OWE0LTI5MzY0ZmY3N2QzOSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzODUxMjgyMCwidXNlcl9pZCI6IjNkZjNiNTc3LWE4ODAtNDE4Ni1hNzQ2LWRkYTZmMDUzNThhYSJ9.aWv5ChukpYyfw7ospfp-yK4TP0z7GNWadyzV3ShmQEU


# Register Request
POST {{BASE_PATH}}/register
Content-Type: application/json

{
  "email": "sriprabandham@gmail.com",
  "name": "Srinidhi P",
  "password": "SuperSecure"
}
####

# LOGIN Request
POST {{BASE_PATH}}/login
Content-Type: application/json

{
  "email": "sriprabandham@gmail.com",
  "password": "SuperSecure"
}
####

# List all expense types
GET {{BASE_PATH}}/expense_types?page=3&per_page=10
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####

# Create an expense type
POST {{BASE_PATH}}/expense_types
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}

{
  "name": "Unwanted Costs - 1"
}
####

# List expenses for logged in user
GET {{BASE_PATH}}/expenses?page=1&per_page=10
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####

# Create an Expense for logged in user.
POST {{BASE_PATH}}/expenses
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}

{
  "expense_type_id": "58db58d3-9b71-4086-9df4-8ea74d794728",
  "amount_spent": 100,
  "spent_on": "2021-12-01T11:50:01.079Z"
}
###

# Logout
DELETE {{BASE_PATH}}/logout
Content-Type: application/json
Authorization: {{AUTH_TOKEN}}
####
